### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by Astroknut** [den-materials/project-03#8]
Error after authentication/on redirect to app. 

Error
    at Strategy.OAuth2Strategy.parseErrorResponse (/Users/astroknut/Desktop/anima/Project3/anima/node_modules/passport-oauth2/lib/strategy.js:329:12)
    at Strategy.OAuth2Strategy._createOAuthError (/Users/astroknut/Desktop/anima/Project3/anima/node_modules/passport-oauth2/lib/strategy.js:376:16)
    at /Users/astroknut/Desktop/anima/Project3/anima/node_modules/passport-oauth2/lib/strategy.js:166:45
    at /Users/astroknut/Desktop/anima/Project3/anima/node_modules/oauth/lib/oauth2.js:191:18
    at passBackControl (/Users/astroknut/Desktop/anima/Project3/anima/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/Users/astroknut/Desktop/anima/Project3/anima/node_modules/oauth/lib/oauth2.js:157:7)
    at ZoneDelegate.invokeTask (/Users/astroknut/Desktop/anima/Project3/anima/node_modules/zone.js/dist/zone-node.js:425:31)
    at Zone.runTask (/Users/astroknut/Desktop/anima/Project3/anima/node_modules/zone.js/dist/zone-node.js:192:47)
    at ZoneTask.invokeTask (/Users/astroknut/Desktop/anima/Project3/anima/node_modules/zone.js/dist/zone-node.js:499:34)
    at IncomingMessage.ZoneTask.invoke (/Users/astroknut/Desktop/anima/Project3/anima/node_modules/zone.js/dist/zone-node.js:488:48)

Can't find similar error through google search.
Working on comparing with Auth0 nodejs tutorial

**Comment by ZebGirouard** [comment]
Chase is on to the next thing, great work, Chase!
